
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: anycasts_development

test:
  <<: *default
  database: anycasts_test

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  <<: *default
  database: anycasts_production
  username: anycasts
  password: <%= ENV['ANYCASTS_DATABASE_PASSWORD'] %>
